[workspace]
members = [
    "WebsiteTutorials/GettingStarted/hello_cargo",
    "WebsiteTutorials/GuessGame",
    "WebsiteTutorials/variables",
]

[profile.release]
codegen-units = 1
debug = true
lto = true 